from app.models import db, ChargeAttack

def seed_charge_attacks():

    ca_list = [
        'Gamma Ray',
        'Thousand Claws',
        'Clairvoyant Bliss',
        'Chaos Legion',
        'Dark Fallen Sword',
        'Verdict Bringer',
        'Sword of Delusion',
        'Alkahest Sphere',
        'Stone Breaker',
        'Heavy Sharklone',
        'Dawnfly Dance II',
        'Freeflutter Dance II',
        'Gilded Heaven Strike',
        'Valley of the Damned',
        'Passione Perpetua',
        'Sa\'ada Barq',
        'Carnage Moon',
        'Hollow Blast',
        '????',
        'Gaia Dora',
        'Minerva Finis',
        'Majestic Boarder',
        'Fury of the Ram',
        'Strast Blast',
        'Awaken Inner Eye',
        'Gewaltfaenge',
        'Rosso Passione',
        'Skyblade Shadowstitch',
        'Krisis Triaina',
        'Aqua Magna',
        'Chaos Impact',
        'Dogged Innocence',
        'Sirius Nova: Last Dive',
        'Frozen Bloom',
        'Paradise Lost',
        'Rumble Breaker',
        'Loewenbein: Jagd ++',
        'Taurus Blight',
        'Infowlible Insight',
        'One with Nature',
        'Ain Soph Aur',
        'Bomb the System',
        'Abyssal Wall',
        'Mirror-Blade Helix',
        'Starless Twilight Slash',
        'Ultimate Colorful Special',
        'Mirror-Blade Helix',
        'Lam Goes Wham',
        'Infinite Monkey Hands: Baboon Blast',
        'Butterfly Effect: Dragonsbane',
        'Holy Ray of Purification',
        'Grace of the Radiant',
        'Bianche Fil',
        'Twilight Blade',
        'Flock to the Future',
        'Tempest',
        'Tentacle Saltatio',
        'Gilded Heaven Strike',
        'Blazing Purification',
        'Sauveur Eclatant',
        'Gefrorene Welt',
        'Ars Magna',
        'Night of Crazy Insanity',
        'Pain Eternal',
        'Elemental Evolution',
        'Sacred Globe',
        'Parhelion Prayer',
        'Paradise Lost',
        'Hyper Lightning Slash',
         ]

    for charge_attacks in ca_list:
        new_charge_attack = ChargeAttack(name=charge_attacks, charge_attack_url='https://grandhcypher-crew.s3.us-west-1.amazonaws.com/images/charge-attacks-and-support-skills/charge-attack.png')
        db.session.add(new_charge_attack)

    db.session.commit()

def undo_charge_attacks():
    db.session.execute('TRUNCATE charge_attacks RESTART IDENTITY CASCADE;')
    db.session.commit()
